config/routes.rb
Rails.application.routes.draw do
  # get "ticket/index", as: "tickets"
  # post "ticket/create"
  # get "ticket/new"
  # get "ticket/edit/:id", to: "ticket#edit", as: "ticket/edit"
  # patch "ticket/update/:id", to: "ticket#update", as: "ticket/update"
  # get "ticket/show/:id", to: "ticket#show", as: "ticket_show"
  # delete "ticket/destroy", to: "ticket#destroy", as: "ticket/destroy"

  resources :project do
    get "add_user", on: :member
    post "add_user_to_project", on: :member
    get "remove_user", on: :member
    delete "remove_user_to_project", on: :member
    resources :ticket
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_navbar.html.erb
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg px-4">
      <a class="navbar-brand" href="/">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Projects", project_index_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
        <div class="my-2 my-lg-0 d-flex align-items-center justify-content-center">
          <% if user_signed_in? %>
            <div>
              <span class="text-white mx-4"><%= current_user.name %></span>
              <% if current_user.designation == "manager" %>
                <span class="text-danger mx-4"><%= current_user.designation %></span>
              <% else %>
                <span class="text-white mx-4"><%= current_user.designation %></span>
              <% end %>
            </div>
            <% end %>
          <%= login_helper %>
        </div>
    </nav>

    <%if notice %>
      <div class="m-2 alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert %>
      <div class="m-2 alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    