config/routes.rb
Rails.application.routes.draw do
  # get "ticket/index", as: "tickets"
  # post "ticket/create"
  # get "ticket/new"
  # get "ticket/edit/:id", to: "ticket#edit", as: "ticket/edit"
  # patch "ticket/update/:id", to: "ticket#update", as: "ticket/update"
  # get "ticket/show/:id", to: "ticket#show", as: "ticket_show"
  # delete "ticket/destroy", to: "ticket#destroy", as: "ticket/destroy"

  resources :project do
    get "add_user", on: :member
    post "add_user_to_project", on: :member
    get "remove_user", on: :member
    delete "remove_user_to_project", on: :member
    resources :ticket
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    if @user
      @tickets_assigned = @user.tickets_assigned
    end
  end
end

app/views/home/index.html.erb
<% if @user %>
<h1>Home</h1>
<%if @tickets_assigned.any? %>
    <% @tickets_assigned.each do |ticket| %>
        <h3><%= link_to ticket.title, project_ticket_path(id: ticket.id, project_id: ticket.project) %></h3>

        <p>Description: <%= ticket.description %></p>
        <p>deadline: <%= ticket.deadline %></p>
        <p>ticket_type: <%= ticket.ticket_type %></p>
        <p>status: <%= ticket.status %></p>
        <p>creator: <%= ticket.creator.name %></p>
        <p>developer: <%= ticket.developer.try(:name) || "Unassigned" %></p>
        <p>Project: <%= ticket.project.name %></p>

        <%= link_to "Edit Ticket", edit_project_ticket_path(project_id: ticket.project.id ,id: ticket.id) %>
    <% end %>

<% else %>
    <h3>No tickets Assigned</h3>
<% end %>

<% else %>
<h1>Login To view the Tickets</h1>
<%end%>