config/routes.rb
Rails.application.routes.draw do
  # get "ticket/index", as: "tickets"
  # post "ticket/create"
  # get "ticket/new"
  # get "ticket/edit/:id", to: "ticket#edit", as: "ticket/edit"
  # patch "ticket/update/:id", to: "ticket#update", as: "ticket/update"
  # get "ticket/show/:id", to: "ticket#show", as: "ticket_show"
  # delete "ticket/destroy", to: "ticket#destroy", as: "ticket/destroy"

  resources :project do
    get "add_user", on: :member
    post "add_user_to_project", on: :member
    get "remove_user", on: :member
    delete "remove_user_to_project", on: :member
    resources :ticket
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :user_projects, dependent: :delete_all
  has_many :user, through: :user_projects
  has_many :tickets, dependent: :delete_all

  validates :name, presence: true
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  include UserCheckable
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = current_user.projects
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        UserProject.create(user: current_user, project: @project)
        format.html { redirect_to project_index_path, notice: "Project was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
    @project = Project.find(params[:id])
    @tickets = @project.tickets
    @current_project = current_user.projects.find(params[:id])
    @team = @project.user
  end

  def edit
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_index_path, notice: "Project was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy!
    respond_to do |format|
      format.html { redirect_to project_index_path, status: :see_other, notice: "Project was successfully destroyed." }
    end
  end

  def add_user
    @project = Project.find(params[:id])
    @users = User.all
    @team = @project.user
  end

  def add_user_to_project
    @project = Project.find(params[:id])
    @user_id = params.permit(:user_id)[:user_id]
    @user = User.find(params[:user_id])

    if @user.projects.include?(@project)
      redirect_to project_path(@project), alert: "User Already assigned to the Project"
    else
      UserProject.create(
        user_id: @user_id,
        project: @project
      )
      redirect_to project_path(@project), notice: "Assigned User to the Project"
    end
  end

  def remove_user
    @project = Project.find(params[:id])
    @users = @project.user
    @team = @project.user
  end

  def remove_user_to_project
    @project = Project.find(params[:id])
    @user = User.find(params[:user_id])

    @tickets_of_project = @project.user.find(params[:user_id]).tickets_assigned.update_all(developer_id: nil)

    if @project.user.include?(@user)
      UserProject.find_by(user_id: @user.id, project_id: @project.id).destroy
      redirect_to project_path(@project), notice: "Removed User from the Project"
    else
      redirect_to project_path(@project), alert: "User not assigned to the Project"
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.permit(:name, :description)
    end
    def check_user!
      redirect_to new_user_session_path unless current_user
    end
end

app/views/project/add_user.html.erb
<h1>Add User <%= @project.name %></h1>
<div class="d-flex align-items-center">
  <h3>Team: </h3>
  <p class="m-0 ml-2">
    <% if @team == nil %>
      No users assigned to this team
    <% else %>
      <% @team.each do |user| %>
      <%= user.name %> | 
      <%end%>
    <% end %>
  </p>
</div>


<%= form_with url: add_user_to_project_project_path(@project), method: :post do |user| %>
  <div>
      <%= user.label :user_id, style: "display: block" %>
      <%= user.collection_select :user_id, @users, :id, :name %>
  </div>

  <div>

    <%= user.submit "Add User to Project", class: "btn btn-primary m-2" %>
  </div>
<% end %>

app/views/project/add_user_to_project.html.erb
<h1>Ad User To Project</h1>

app/views/project/create.html.erb
<h1>Ticket#create</h1>
<p>Find me in app/views/ticket/create.html.erb</p>

app/views/project/destroy.html.erb
<h1>Ticket#destroy</h1>
<p>Find me in app/views/ticket/destroy.html.erb</p>

app/views/project/edit.html.erb
<h1>Edit a new Project</h1>

<%= form_with(model: @projects, url: project_path, method: :patch) do |project| %>
  <div>
    <%= project.label :name, style: "display: block" %>
    <%= project.text_field :name, value: @project.name %>
  </div>

  <div>
    <%= project.label :description, style: "display: block" %>
    <%= project.text_field :description, value: @project.description %>
  </div>

  <div>
    <%= project.submit "Update project", class: "btn btn-primary m-2" %>
    
  </div>

<% end %>

<%= button_to "Cancel", project_path(@project), method: :get, data: { confirm: "Are you sure about that?", turbo_confirm: "Are you sure about that?" }, class: "btn btn-primary m-2 my-sm-0" %>

app/views/project/index.html.erb
<h1>Projects</h1>
 <p><%=@user%></p>
<%# <a href="portfolios/new">Create New Portfolio Item</a> %>

<% if current_user.designation == "manager" %>
<%= link_to "Create New Project", new_project_path %>
<% end %>
<br>

<% @projects.each do |project| %>
  <p><%= link_to project.name, project_path(project.id) %></p>
  <p><%= project.description %></p>

  <%#= image_tag project.thumb_image ? project.thumb_image : "https://www.placeholder.com/100x100" %>
  <% if current_user.designation == "manager" %>
    <%= button_to "Delete", project_path(id: project.id), method: :delete, data: { confirm: " ?", turbo_confirm: "Are you sure about that?" }, class: "btn btn-primary my-2 my-sm-0" %>
  <% end %>
<% end %>

app/views/project/new.html.erb
<h1>Create a new Project</h1>

<%= form_with(model: @projects, url: project_index_path, method: :post) do |project| %>
  <div>
    <%= project.label :name, style: "display: block" %>
    <%= project.text_field :name %>
  </div>

  <div>
    <%= project.label :description, style: "display: block" %>
    <%= project.text_field :description %>
  </div>

  <div>
    <%= project.submit "Create project", class: "btn btn-primary m-2" %>
  </div>

<% end %>

app/views/project/remove_user.html.erb
<h1>Remove User <%= @project.name %></h1>

<div class="d-flex align-items-center">
  <h3>Team: </h3>
  <p class="m-0 ml-2">
    <% if @team == nil %>
      No users assigned to this team
    <% else %>
      <% @team.each do |user| %>
        <%= user.name %> | 
      <%end%>
    <% end %>
  </p>
</div>

<%= form_with url: remove_user_to_project_project_path(@project), method: :delete do |user| %>
  <div>
      <%= user.label :user_id, style: "display: block" %>
      <%= user.collection_select :user_id, @users, :id, :name %>
  </div>

  <div>
    <%= user.submit "Remove", class: "btn btn-primary m-2", data: { turbo_confirm: "Are you sure about that?" } %>
  </div>
<% end %>

app/views/project/show.html.erb
<h1><%= @project.name %></h1>

<div class="d-flex align-items-center">
  <h3>Team: </h3>
  <p class="m-0 ml-2">
    <% if @team == nil %>
      No users assigned to this team
    <% else %>
      <% @team.each do |user| %>
      <%= user.name %> | 
      <%end%>
    <% end %>
  </p>
</div>

<p><%= @project.description %></p>

<% if current_user.designation == "manager" %>
    <%= link_to "Edit Project", edit_project_path(@project.id) %>
    <br>
    <%= link_to "Add User to Project", add_user_project_path(@project.id) %>
    <br>
    <%= link_to "Remove User from Project", remove_user_project_path(@project.id) %>
    <p><%=link_to "Create new Ticket", new_project_ticket_path(project_id: @project) %></p>
<% end %>
<h3>Tickets</h3>
<% @tickets.each do |ticket| %>
    <p><%= link_to ticket.title, project_ticket_path(@project, ticket.id) %></p>

    <p>Description: <%= ticket.description %></p>
    <p>deadline: <%= ticket.deadline %></p>
    <p>ticket_type: <%= ticket.ticket_type %></p>
    <p>status: <%= ticket.status %></p>
    <p>creator: <%= ticket.creator.name %></p>
    <p>developer: <%= ticket.developer.try(:name) || "Unassigned" %></p>
    <p>Project: <%= ticket.project.name %></p>

    <%#= image_tag ticket.thumb_image ? ticket.thumb_image : "https://www.placeholder.com/100x100" %>
    <% if current_user.designation == "manager" %>
        <%= button_to "Delete Ticket", project_ticket_path(project_id: @project ,id: ticket.id), method: :delete, data: { confirm: "Are you sure about that?", turbo_confirm: "Are you sure about that?" }, class: "btn btn-primary m-2 my-sm-0" %>
    <% end %>
<% end %>

<% if current_user.designation == "manager" %>
    <%= button_to "Delete Project", project_path(id: @project.id), method: :delete, data: { confirm: "Are you sure about that?", turbo_confirm: "Are you sure about that?" }, class: "btn btn-primary m-2 my-sm-0" %>
<% end %>

app/views/project/update.html.erb
<h1>Ticket#update</h1>
<p>Find me in app/views/ticket/update.html.erb</p>