config/routes.rb
Rails.application.routes.draw do
  # get "ticket/index", as: "tickets"
  # post "ticket/create"
  # get "ticket/new"
  # get "ticket/edit/:id", to: "ticket#edit", as: "ticket/edit"
  # patch "ticket/update/:id", to: "ticket#update", as: "ticket/update"
  # get "ticket/show/:id", to: "ticket#show", as: "ticket_show"
  # delete "ticket/destroy", to: "ticket#destroy", as: "ticket/destroy"

  resources :project do
    get "add_user", on: :member
    post "add_user_to_project", on: :member
    get "remove_user", on: :member
    delete "remove_user_to_project", on: :member
    resources :ticket
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :creator, class_name: "User"
  belongs_to :developer, class_name: "User", optional: true
  belongs_to :project, class_name: "Project"

  has_one_attached :image
  validate :valid_image_content_type


  TICKET_TYPES = [ "bug", "feature" ]
  BUG_STATUS = [ "new", "started", "resolved" ]
  FEATURE_STATUS = [ "new", "started", "completed" ]
  validates :status, inclusion: { in: BUG_STATUS + FEATURE_STATUS } # no need as on front end we already showing only these option like its a selectable field
  validates :ticket_type, inclusion: { in: TICKET_TYPES }
  # enum :status, {
  #   new: "new",
  #   started: "started",
  #   resolved: "resolved",
  #   completed: "completed"
  # }

  # enum :ticket_type, {
  #   bug: "bug",
  #   feature: "feature"
  # }


  # why not use enum
  # use enum

  validates :title, :deadline, :ticket_type, :status, :creator_id, :project_id, presence: true

  private
  def valid_image_content_type
    if image.attached? &&
       ![ "image/png", "image/gif" ].include?(image.content_type)

      errors.add(:image, "must be PNG or GIF")
    end
  end
end

app/controllers/ticket_controller.rb
class TicketController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]
  include UserCheckable
  def index
    @tickets = Ticket.all
  end

  def new
    @project = Project.find(params[:project_id])
    @tickets = @project.tickets.new
    @users = @project.user.where(designation: "developer")
    @current_user = current_user
    @my_ticket_type = @tickets.ticket_type
    @statuses = set_statuses(@my_ticket_type)
  end

  def create
    @current_user = current_user
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.new(params.require(:ticket).permit(:title, :description, :deadline, :ticket_type, :status, :creator_id, :developer_id, :project_id, :image))
    @my_ticket_type = @ticket.ticket_type || "bug"
    @statuses = set_statuses(@my_ticket_type)
    @users = @project.user.where(designation: "developer")

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to project_path(id: @project), notice: "Ticket was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
    @project = Project.find(params[:project_id])
    @tickets = @project.tickets.new
    @users = @project.user.where(designation: "developer")
    @current_user = current_user
    @my_ticket_type = @ticket.ticket_type || "bug"
    @statuses = set_statuses(@my_ticket_type)
  end

  def update
    @project = Project.find(params[:project_id])
    @current_user = current_user
    @users = @project.user
    respond_to do |format|
      if @ticket.update(params.require(:ticket).permit(:title, :description, :deadline, :ticket_type, :status, :creator_id, :developer_id, :project_id, :image))
        format.html { redirect_to project_ticket_path(project_id: @project, id: @ticket), notice: "Ticket was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @ticket.destroy!
    respond_to do |format|
      redirect_to project_path(@project), status: :see_other, notice: "ticket was successfully destroyed."
    end
  end

  private
    def set_ticket
      @project = Project.find(params[:project_id])
      @ticket_found = Ticket.find_by(id: params[:id])

      if @ticket_found
        @ticket = Ticket.find(params[:id])
      else
        redirect_to project_path(@project)
      end
    end

    def ticket_params
      params.permit(:title, :description, :deadline, :ticket_type, :status, :creator_id, :developer_id, :project_id, :image, :id)
    end

    def set_statuses(my_ticket_type)
      if my_ticket_type == "feature"
        Ticket::FEATURE_STATUS
      else
        Ticket::BUG_STATUS
      end
    end
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/ticket/edit.html.erb
<h1>Edit Ticket</h1>

<%= form_with(model: @ticket, url: project_ticket_path(project_id: @project), method: :patch) do |t| %>
    <h3>For: <%= @project.name %></h3>

    <div>
      <p>Creator: <%= @current_user.name %></p>
    </div>

    <div>
      <%= t.hidden_field :creator_id, value: current_user.id %> 
    </div>
    
    <div>
      <%= t.label :title, style: "display: block" %>
      <%= t.text_field :title %>
    </div>

    <div>
      <%= t.label :description, style: "display: block" %>
      <%= t.text_field :description%>
    </div>
    
    <div>
      <%= t.label :deadline, style: "display: block" %>
      <%= t.date_field :deadline %>
    </div>


    <div>
      <%= t.label :ticket_type, style: "display: block" %>
      <%= t.select :ticket_type, Ticket::TICKET_TYPES, { id: 'ticket_type_select'}%>
    </div>

    <div>
      <%= t.label :status, style: "display: block" %>
      <%= t.select :status, @statuses %>
    </div>

    <div>
        <%= t.label :developer_id, style: "display: block" %>
        <%= t.collection_select :developer_id, @users, :id, :name %>
    </div>

    <div class="field">
      <%= t.label :image, 'Upload Screenshot' %>
      <%= t.file_field :image, accept: "image/png, image/gif" %>
    </div>

    <% if @ticket.image.attached? %>
      <%= image_tag @ticket.image, class: "img-size" %>
    <% else %>
      <p>No image available.</p>
    <% end %>
    <br>
    <div>
      <%= t.submit %>
    </div>
<% end %>

app/views/ticket/index.html.erb
<h1>Tickets</h1>
 
<%# <a href="portfolios/new">Create New Portfolio Item</a> %>
<% if current_user.designation == "manager" %>
<%= link_to "Create New Ticket", project_ticket_index_path%>
<% end %>
<br>

<% @tickets.each do |ticket| %>
    <p><%= link_to ticket.title, project_ticket_path(id: ticket.id) %></p>

    <p><%= ticket.description %></p>
    <p><%= ticket.deadline %></p>
    <p><%= ticket.ticket_type %></p>
    <p><%= ticket.status %></p>
    <p><%= ticket.creator.name %></p>
    <p><%= ticket.developer.name %></p>
    <p><%= ticket.project.name %></p>

    <%#= image_tag ticket.thumb_image ? ticket.thumb_image : "https://www.placeholder.com/100x100" %>
    <% if current_user.designation == "manager" %>
        <%= button_to "Delete", project_ticket_path(id: ticket), method: :delete, data: { confirm: "Are you sure about that?", turbo_confirm: "Are you sure about that?" }, class: "btn btn-primary my-2 my-sm-0" %>
    <% end %>
<% end %>

app/views/ticket/new.html.erb
<h1>Create a new Ticket</h1>
<p>For: <%= @project.name %></p>

<%= form_with(model: @tickets, url: project_ticket_index_path(project_id: @project), method: :post) do |ticket| %>
  
  <div>
    <p>Creator: <%= @current_user.name %></p>
  </div>

   <div>
    <%= ticket.hidden_field :creator_id, value: current_user.id %> 
  </div>

  <div>
    <%= ticket.label :title, style: "display: block" %>
    <%= ticket.text_field :title %>
  </div>

  <div>
    <%= ticket.label :description, style: "display: block" %>
    <%= ticket.text_field :description %>
  </div>

  <div>
    <%= ticket.label :deadline, style: "display: block" %>
    <%= ticket.date_field :deadline %>
  </div>

  <div>
      <%= ticket.label :ticket_type, class: "form-label" %>
      <%= ticket.select :ticket_type, options_for_select([['Feature', 'feature'], ['Bug', 'bug']]), { include_blank: "Select Type" }, class: "form-select", id: "bug_type_select" %>
  </div>

  <div>
      <%= ticket.label :status, class: "form-label" %>
      <%= ticket.select :status, options_for_select([]), { include_blank: "Select Status" }, class: "form-select", id: "status_select"  %>
  </div>

  <div class="field">
    <%= ticket.label :image, 'Upload Screenshot' %>
    <%= ticket.file_field :image, accept: "image/png, image/gif" %>
  </div>

  <div>
      <%= ticket.label :developer_id, style: "display: block" %>
      <%= ticket.collection_select :developer_id, @users, :id, :name %>
  </div>

  <div>
    <%= ticket.submit "Create Ticket", class: "btn btn-primary m-2" %>
  </div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const ticketTypeSelect = document.getElementById("bug_type_select");
    const statusSelect = document.getElementById("status_select");
    const statusOptions = {
      feature: ['new', 'started', 'completed'],
      bug: ['new', 'started', 'resolved']
    };

    ticketTypeSelect.addEventListener("change", function() {
      const selectedType = this.value;
      const options = statusOptions[selectedType] || [];
      statusSelect.innerHTML = '';

      options.forEach(function(status) {
        const option = document.createElement("option");
        option.value = status;
        option.textContent = status;
        statusSelect.appendChild(option);
      });

      statusSelect.value = "";
    });
  });

  (function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem('firstLoad') )
    {
      localStorage['firstLoad'] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem('firstLoad');
  }
})();

</script>
<% end %>

app/views/ticket/show.html.erb
<h1><%= @ticket.title %></h1>

<p>Description: <%= @ticket.description %></p>
<p>deadline: <%= @ticket.deadline %></p>
<p>ticket_type: <%= @ticket.ticket_type %></p>
<p>status: <%= @ticket.status %></p>
<p>creator: <%= @ticket.creator.name %></p>
<p>developer: <%= @ticket.developer.try(:name) || "Unassigned" %></p>
<p>Project: <%= @ticket.project.name %></p>

<% if @ticket.image.attached? %>
  <%= image_tag @ticket.image, class: "img-size" %>
<% else %>
  <p>No image available.</p>
<% end %>

<br>
<%= link_to "Edit Ticket", edit_project_ticket_path(@project.id ,@ticket.id) %>

<% if current_user.designation == "manager" %>
  <%= button_to "Delete Ticket", project_ticket_path(id: @ticket.id), method: :delete, data: { confirm: "Are you sure about that?", turbo_confirm: "Are you sure about that?" }, class: "btn btn-primary m-2 my-sm-0" %>
<% end %>